version: "3.8"

services:
  rclone-mount:
    build:
      context: .
    network_mode: bridge
    privileged: true
    environment: 
      - MOUNT_PATH=alist    #配置名称
      - REMOTE_NAME=onedirve   #路径
    volumes:
      - ./media:/mnt/rclone:shared
      - ./config:/config/
    devices:
      - /dev/fuse:/dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped