version: "3.8"

services:
  rclone-mount:
    build: .
    container_name: rclone-mount
    network_mode: bridge
    environment: 
      - MOUNT_PATH=alist    #配置名称
      - REMOTE_NAME=onedirve   #路径
    volumes:
      - ./rclone:/mnt/rclone:rshared
      - ./config:/config/
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    restart: unless-stopped
